const basewidth = 300;
const baseheight = 60;

const tarray = {
    "excited":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "duration": 250,
        "ease": "out",
        "easev": 0.7,
        "color": 0,
        "fontw": 500,
        "fontstyle": "italic",
        "stroke": 5
    },

    "interested":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": 85,
        "opacity": 1,
        "duration": 500,
        "ease": "out",
        "easev": 0.9,
        "color": 0,
        "fontw": 400,
        "fontstyle": "normal",
        "stroke": 5
    },

    "questioning":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": -90,
        "opacity": 1,
        "duration": 1000,
        "ease": "in",
        "easev": 2,
        "color": 1,
        "fontw": 300,
        "fontstyle": "normal",
        "stroke": 5
    },

    "right":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "duration": 1000,
        "ease": "inout",
        "easev": 0.3,
        "color": 1,
        "fontw": 100,
        "fontstyle": "normal",
        "stroke": 5
    },

    "unsure":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "duration": 1000,
        "ease": "inout",
        "easev": 4,
        "color": 1,
        "fontw": 100,
        "fontstyle": "normal",
        "stroke": 5
    },

    "neutral":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "duration": 500,
        "ease": "linear",
        "easev": 0,
        "color": 2,
        "fontw": 400,
        "fontstyle": "normal",
        "stroke": 5
    },

    "sarcasm":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "duration": 500,
        "ease": "linear",
        "easev": 0,
        "color": 2,
        "fontw": 400,
        "fontstyle": "italic",
        "stroke": 5
    },

    "umno":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "duration": 1000,
        "ease": "inout",
        "easev": 2,
        "color": 3,
        "fontw": 500,
        "fontstyle": "regular",
        "stroke": 5
    },

    "no":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "duration": 500,
        "ease": "in",
        "easev": 4,
        "color": 3,
        "fontw": 700,
        "fontstyle": "regular",
        "stroke": 5
    },

    "bigno":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "duration": 500,
        "ease": "in",
        "easev": 6,
        "color": 4,
        "fontw": 900,
        "fontstyle": "italic",
        "stroke": 5
    },

    "excitedPP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0,
        "duration": 250,
        "stroke": 9
    },

    "excitedPM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 250,
        "stroke": 7
    },

    "excitedPm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.6,
        "duration": 1000,
        "stroke": 5
    },

    "excitedPD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.6,
        "duration": 1000,
        "stroke": 3
    },

    "excitedMP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 250,
        "stroke": 7
    },

    "excitedMM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 250,
        "stroke": 7
    },

    "excitedMm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.6,
        "duration": 500,
        "stroke": 5
    },

    "excitedMD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.6,
        "duration": 1000,
        "stroke": 5
    },

    "excitedmP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 250,
        "stroke": 7
    },

    "excitedmM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 250,
        "stroke": 5
    },

    "excitedmm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 500,
        "stroke": 5
    },

    "excitedmD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.9,
        "duration": 1000,
        "stroke": 7
    },

    "excitedDP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0,
        "duration": 1000,
        "stroke": 9
    },

    "excitedDM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.3,
        "duration": 1000,
        "stroke": 9
    },

    "excitedDm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.9,
        "duration": 500,
        "stroke": 5
    },

    "excitedDD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "out",
        "easev": 0.7,
        "fontw": 500,
        "fontstyle": "italic",
        "color": 0.9,
        "duration": 1000,
        "stroke": 9
    },

    "interestedP":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": 85,
        "opacity": 1,
        "ease": "out",
        "easev": 0.9,
        "fontw": 400,
        "fontstyle": "normal",
        "color": 0,
        "duration": 250,
        "stroke": 9
    },

    "interestedM":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": 85,
        "opacity": 1,
        "ease": "out",
        "easev": 0.9,
        "fontw": 400,
        "fontstyle": "normal",
        "color": 0,
        "duration": 500,
        "stroke": 7
    },

    "interestedm":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": 85,
        "opacity": 1,
        "ease": "out",
        "easev": 0.9,
        "fontw": 400,
        "fontstyle": "normal",
        "color": 0.3,
        "duration": 500,
        "stroke": 5
    },

    "interestedD":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": 85,
        "opacity": 1,
        "ease": "out",
        "easev": 0.9,
        "fontw": 400,
        "fontstyle": "normal",
        "color": 0.3,
        "duration": 1000,
        "stroke": 3
    },

    "questioningP":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": -90,
        "opacity": 1,
        "ease": "in",
        "easev": 2,
        "fontw": 300,
        "fontstyle": "normal",
        "color": 1,
        "duration": 500,
        "stroke": 9
    },

    "questioningM":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": -90,
        "opacity": 1,
        "ease": "in",
        "easev": 2,
        "fontw": 300,
        "fontstyle": "normal",
        "color": 1,
        "duration": 1000,
        "stroke": 9
    },

    "questioningm":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": -90,
        "opacity": 1,
        "ease": "in",
        "easev": 2,
        "fontw": 300,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 1000,
        "stroke": 7
    },

    "questioningD":{
        "width": basewidth,
        "height": baseheight,
        "x": w-300,
        "xr": 0,
        "y": -90,
        "opacity": 1,
        "ease": "in",
        "easev": 2,
        "fontw": 300,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 1000,
        "stroke": 5
    },

    "rightPP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 500,
        "stroke": 9
    },

    "rightPM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 500,
        "stroke": 7
    },

    "rightPm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 1000,
        "stroke": 5
    },

    "rightPD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 2000,
        "stroke": 3
    },

    "rightMP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 1000,
        "stroke": 9
    },

    "rightMM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 1000,
        "stroke": 7
    },

    "rightMm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 1000,
        "stroke": 5
    },

    "rightMD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 2000,
        "stroke": 3
    },

    "rightmP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 1000,
        "stroke": 7
    },

    "rightmM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 2000,
        "stroke": 7
    },

    "rightmm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 2000,
        "stroke": 5
    },

    "rightmD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 2000,
        "stroke": 5
    },

    "rightDP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 2000,
        "stroke": 7
    },

    "rightDM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 2000,
        "stroke": 7
    },

    "rightDm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 2000,
        "stroke": 5
    },

    "rightDD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 0.3,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 2000,
        "stroke": 5
    },

    "unsurePP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 500,
        "stroke": 9
    },

    "unsurePM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 500,
        "stroke": 7
    },

    "unsurePm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 1000,
        "stroke": 5
    },

    "unsurePD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 2000,
        "stroke": 3
    },

    "unsureMP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 1000,
        "stroke": 9
    },

    "unsureMM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 1000,
        "stroke": 7
    },

    "unsureMm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 1000,
        "stroke": 5
    },

    "unsureMD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 2000,
        "stroke": 3
    },

    "unsuremP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 1000,
        "stroke": 7
    },

    "unsuremM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 2000,
        "stroke": 7
    },

    "unsuremm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 2000,
        "stroke": 5
    },

    "unsuremD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 2000,
        "stroke": 5
    },

    "unsureDP":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.9,
        "duration": 2000,
        "stroke": 7
    },

    "unsureDM":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.6,
        "duration": 2000,
        "stroke": 7
    },

    "unsureDm":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1.3,
        "duration": 2000,
        "stroke": 5
    },

    "unsureDD":{
        "width": basewidth,
        "height": baseheight,
        "x": -300,
        "xr": w+300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 4,
        "fontw": 100,
        "fontstyle": "normal",
        "color": 1,
        "duration": 2000,
        "stroke": 5
    },

    "umnoP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 2,
        "fontw": 500,
        "fontstyle": "regular",
        "color": 3.9,
        "duration": 500,
        "stroke": 9
    },

    "umnoM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 2,
        "fontw": 500,
        "fontstyle": "regular",
        "color": 3.6,
        "duration": 1000,
        "stroke": 7
    },

    "umnom":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 2,
        "fontw": 500,
        "fontstyle": "regular",
        "color": 3.6,
        "duration": 2000,
        "stroke": 5
    },

    "umnoD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "inout",
        "easev": 2,
        "fontw": 500,
        "fontstyle": "regular",
        "color": 3.9,
        "duration": 2000,
        "stroke": 3
    },

    "noP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 4,
        "fontw": 700,
        "fontstyle": "regular",
        "color": 3.9,
        "duration": 500,
        "stroke": 9
    },

    "noM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 4,
        "fontw": 700,
        "fontstyle": "regular",
        "color": 3.6,
        "duration": 1000,
        "stroke": 7
    },

    "nom":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 4,
        "fontw": 700,
        "fontstyle": "regular",
        "color": 3.3,
        "duration": 2000,
        "stroke": 5
    },

    "noD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 4,
        "fontw": 700,
        "fontstyle": "regular",
        "color": 3,
        "duration": 2000,
        "stroke": 3
    },

    "bignoPP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 250,
        "stroke": 9
    },

    "bignoPM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.6,
        "duration": 500,
        "stroke": 7
    },

    "bignoPm":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.6,
        "duration": 500,
        "stroke": 5
    },

    "bignoPD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 1000,
        "stroke": 3
    },

    "bignoMP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 500,
        "stroke": 7
    },

    "bignoMM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.6,
        "duration": 1000,
        "stroke": 7
    },

    "bignoMm":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.6,
        "duration": 1000,
        "stroke": 5
    },

    "bignoMD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 1000,
        "stroke": 3
    },

    "bignomP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.3,
        "duration": 500,
        "stroke": 9
    },

    "bignomM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.3,
        "duration": 500,
        "stroke": 7
    },

    "bignomm":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 1000,
        "stroke": 5
    },

    "bignomD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 1000,
        "stroke": 3
    },

    "bignoDP":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4,
        "duration": 1000,
        "stroke": 9
    },

    "bignoDM":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.3,
        "duration": 1000,
        "stroke": 7
    },

    "bignoDm":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.6,
        "duration": 500,
        "stroke": 5
    },

    "bignoDD":{
        "width": basewidth,
        "height": baseheight,
        "x": w+300,
        "xr": -300,
        "y": 10,
        "opacity": 1,
        "ease": "in",
        "easev": 6,
        "fontw": 900,
        "fontstyle": "italic",
        "color": 4.9,
        "duration": 500,
        "stroke": 3
    },

};